apiVersion: apps/v1
kind: Deployment
metadata:
  name: famyoutube
  labels:
    app: famyoutube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: famyoutube
  template:
    metadata:
      labels:
        app: famyoutube
    spec:
      containers:
      - name: famyoutube
        image: nirushadoc/fampay
        ports:
        - containerPort: 8000
