# Generated by Django 3.1.4 on 2020-12-31 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='datetime1',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
